### ISSUE TITLE
bloating Log File consumes all hard drive memory

### ISSUE THREAD

**Issue by MatPopp** [FAU-LAP/NOMAD-CAMELS#43]
It seems as all measurement data is printed to the log-file... This eats up all hard drive memory when performing long measurements. 

![grafik](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/27500989/f61cfb0f-cc09-4d95-b1cc-8155f4c1291f)

suggestions: 
* limit size of log file 
* optional: make size limit adjustable in settings
*  ...

PS: 
congratulations, CAMELS has produced more than 140GB of data outside of LAP ;)   (still some GB without log file)

**Comment by Jo-Leh** [comment]
Thanks a lot for pointing this out! And sorry to clutter your hard drive :/
This problem is fixed in the next release (we plan to release it sometime next week). We added options for the maximum file size and also to specify the logging-level. So far it was set to "DEBUG", which gets quite large rather fast. The default setting will then be "Warning", which should include only the relevant logs for most users.
