### ISSUE TITLE
Minor feature request in measurement protocols and data saving options

### ISSUE THREAD

**Issue by SebLoUniv** [FAU-LAP/NOMAD-CAMELS#46]
It would be great if there was the option do "comment out" sections of sequences in the measurement protocol, e.g. an option to hide "read channels" without deleting it.

![Screenshot 2023-08-02 155513](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/97531605/5af9ef6f-5226-48ee-bfe4-eb99491f4253)

It also would be great to have the option to not record data in a datafile, maybe as an additional option as tick-box in the screenshot below.

![Screenshot 2023-08-02 155513](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/97531605/10e710e0-77dd-4431-87d7-f484411b147c)

**Comment by lapmk** [comment]
Ad 1: A "comment out" option would be indeed a good idea.
Ad 2: Can you explain the reasoning of not storing data? In my point of view, data should always be stored (later you may delete the file if useless). Otherwise you might miss excellent data if not stored.

**Comment by lapmk** [comment]
Ad 2: I understand. I'm still not convinced. This would be a dangerous option (imagine starting a large measurement session and forgetting to enable save data ... less dangerous to save everything and delete useless data later).

**Comment by Jo-Leh** [comment]
Ad 1: This is a very nice functionality. It is going to be implemented in the next release.
Ad 2: We decided to not include not-saving of data. It would not fit well to the FAIR-data approach of NOMAD-CAMELS since sometimes also "bad" data may be of value later. It is left open to the user to use a dummy-sample or add something like "test" into the session-line in the UI for flagging test-measurements.

**Comment by SebLoUniv** [comment]
Ad 2: I would propose a test checkbox somewhere near the "play" buttons, which writes "test-" or something along the lines in front or at the end of the session name.
